spring:
  application:
    name: ranpo-backend
  profiles:
    active: local
---
# Datasource
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
---
# JPA
spring:
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
# OAuth2
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${OAUTH2_REDIRECT_URI_GOOGLE}
            client-id: ${OAUTH2_CLIENT_ID_GOOGLE}
            client-secret: ${OAUTH2_CLIENT_SECRET_GOOGLE}
            scope:
              - email
              - profile
          naver:
            redirect-uri: ${OAUTH2_REDIRECT_URI_NAVER}
            client-id: ${OAUTH2_CLIENT_ID_NAVER}
            client-secret: ${OAUTH2_CLIENT_SECRET_NAVER}
            authorization-grant-type: authorization_code
            client-name: naver
            scope:
              - name
              - email
          kakao:
            redirect-uri: ${OAUTH2_REDIRECT_URI_KAKAO}
            client-id: ${OAUTH2_CLIENT_ID_KAKAO}
            client-secret: ${OAUTH2_CLIENT_SECRET_KAKAO}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
---
# JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}